# image will be published to ghcr.io/<user>/<name>
name: my-ublue
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/base-main
image-version: 39 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr
          # copies config/files/usr into your image's /usr.
          # put configuration files you want in /etc/ on a booted system 
          # in /usr/etc/ in the image. read more in files module reference.
      - lib: /lib

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/alebastr/sway-extras/repo/fedora-%OS_VERSION%/alebastr-sway-extras-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/charlieqle/rpmspec/repo/fedora-%OS_VERSION%/charlieqle-rpmspec-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/solopasha/hyprland/repo/fedora-%OS_VERSION%/solopasha-hyprland-fedora-%OS_VERSION%.repo
      - https://download.opensuse.org/repositories/hardware:/razer/Fedora_%OS_VERSION%/hardware:razer.repo
      - https://terra.fyralabs.com/terra.repo
    install:
      - adw-gtk3-theme
      - adwaita-icon-theme
      - bluez
      - bluez-libs
      - brightnessctl
      - btop
      - corectrl
      - fprintd
      - fprintd-pam
      - gjs
      - gnome-bluetooth-libs
      - gnome-disk-utility
      - gnome-keyring
      - gnome-keyring-pam
      - gnome-online-accounts
      - grim
      - gtk3
      - gtk4
      - gtk-layer-shell
      - gtk4-layer-shell
      - gvfs
      - gvfs-fuse
      - gvfs-smb
      - gvfs-mtp
      - hyprlock
      - kanshi
      - libadwaita
      - libatomic
      - libratbag-ratbagd
      - lm_sensors
      - nautilus
      - nautilus-extensions
      - nautilus-python
      - ncdu
      - nm-connection-editor
      - nvtop
      - openrazer-meta
      - openresolv
      - openvpn
      - playerctl
      - polkit-gnome
      - pulseaudio-utils
      - qt5-qtwayland
      - qt6-qtwayland
      - slurp
      - starship
      - swayidle
      - swww
      - udiskie
      - wayfire-git
      - wayfire-plugins-extra-git
      - wayland-logout
      - wayvnc
      - wf-shell
      - wl-clipboard
      - wlr-randr
      - wofi
      - xdg-desktop-portal-gtk
      - xdg-desktop-portal-wlr
      - xrandr
      - yubikey-manager-qt
    remove:
      - firefox
      - firefox-langpacks

  - type: default-flatpaks
    notify: true
    user:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub (user)"
      install:
        - org.gnome.Calculator
        - org.gnome.Calendar
        - org.gnome.Snapshot
        - org.gnome.Characters
        - org.gnome.Evince
        - org.gnome.FileRoller
        - org.gnome.font-viewer
        - org.gnome.Loupe
        - org.gnome.Logs
        - org.gnome.NautilusPreviewer
        - org.gnome.TextEditor
        - org.gnome.Weather
        - org.fedoraproject.MediaWriter
        - com.github.tchx84.Flatseal
        - org.mozilla.firefox
        - com.raggesilver.BlackBox
        - com.visualstudio.code
        - org.flatpak.Builder
        - com.usebottles.bottles
        - com.valvesoftware.Steam
        - com.vysp3r.ProtonPlus
        - com.github.Matoking.protontricks
        - dev.vencord.Vesktop
        - io.github.Foldex.r2mod
        - org.prismlauncher.PrismLauncher
        - com.github.rafostar.Clapper
        - com.yubico.yubioath
        - com.github.unrud.VideoDownloader
        - com.github.flxzt.rnote
        - com.bitwarden.desktop
        - org.pipewire.Helvum
        - org.pulseaudio.pavucontrol

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

  - type: akmods
    base: main
    install:
      - openrazer
      - openrgb
      - ryzen-smu
      - winesync
